# Copyright (c) 2026 Luis Manuel Cousido Hermida. All rights reserved.
import json
import hashlib

import numpy as np
import pytest

from hydra.training import base_corpus as bc
from hydra.training import base_quality as q

from .test_base_corpus import prose, write


def test_ocr_repair_joins_hyphenation_wrapped_lines_and_drops_page_furniture():
    shy = chr(0x00AD)
    page = "\n".join(["CAPÍTULO PRIMERO", "Era una tarde de in-", "vierno y el puerto", "estaba en calma.", "12",
                      "", f"La gente con{shy} suelo volvía a casa.", "- 13 -", "CAPÍTULO PRIMERO", "Fin.",
                      "CAPÍTULO PRIMERO", "x", "CAPÍTULO PRIMERO"])
    repaired = q.repair_ocr(page)
    assert "Era una tarde de invierno y el puerto estaba en calma." in repaired
    assert "consuelo" in repaired and "12" not in repaired.split("\n") and "- 13 -" not in repaired
    assert "CAPÍTULO PRIMERO" not in repaired  # running header repeated on every page


def test_gopher_rules_reject_repetition_symbols_and_wrong_language():
    good = prose(10, 60)
    assert q.quality_problem(good, "pleias_parquet") is None
    assert q.quality_problem(" ".join(["la casa grande del puerto"] * 80), "pleias_parquet").startswith(("dup", "top"))
    assert q.quality_problem(good + " ..." * 400, "pleias_parquet") == "symbols"
    english = "The committee will review the annual report and publish the accounts before summer. " * 1
    assert q.quality_problem(" ".join(english + str(i) for i in range(30)), "pleias_parquet") == "language"
    assert q.quality_problem("palabra " * 20, "pleias_parquet") == "too_few_words"


def test_law_keeps_its_formulaic_repetition_and_markdown_its_repeated_code():
    law = "\n".join(f"Artículo {i}. De conformidad con lo dispuesto en el artículo anterior, la autoridad "
                    f"competente resolverá en el plazo de tres meses desde la solicitud." for i in range(60))
    assert q.repetition_problem(law) is not None  # Gopher alone would reject it...
    assert q.quality_problem(law, "boe") is None  # ...the calibrated BOE rules keep it
    fence = "```bash\npip install hydra\n```\n"
    readme = "# Instalación\n" + prose(11, 12) + "\n\n" + "".join(fence + prose(20 + i, 2) + "\n\n" for i in range(6))
    assert q.quality_problem(readme, "stack_markdown") is None


def test_ocr_noise_uses_the_reference_lexicon():
    clean = prose(13, 40)
    lexicon = q.build_lexicon([clean] * 3)
    assert q.quality_problem(clean, "pleias_parquet", lexicon) is None
    garbled = " ".join(w if i % 3 else w[::-1] + "f" for i, w in enumerate(clean.split()))
    assert q.quality_problem(garbled, "pleias_parquet", lexicon) == "ocr_noise"


def test_code_rules():
    ok = "".join(f"def total_{i}(items):\n    return sum(items) + {i}\n\n" for i in range(5))
    assert q.code_problem(ok) is None
    assert q.code_problem("print 'python 2'\n") == "syntax"
    assert q.code_problem("# Auto-generated file. Do not edit.\n" + ok) == "autogenerated"
    assert q.code_problem(ok + "BLOB = '" + "QUJD" * 100 + "'\n") == "data_blob"
    assert q.code_problem("x = 1\n" + "y = [" + "1, " * 600 + "]\n") == "long_lines"
    assert q.code_problem("return 1\n") == "syntax"
    assert q.code_problem("def f(a, a):\n    return a\n") == "syntax"
    assert q.code_problem("") == "empty"


def test_empty_ocr_lexicon_cannot_disable_the_filter():
    with pytest.raises(ValueError, match="empty"):
        q.quality_problem(prose(13, 40), "pleias_parquet", frozenset())


def test_long_shingle_boundary_does_not_change_shared_hash_sampling(monkeypatch):
    monkeypatch.setattr(q, "MAX_SHINGLES", 200)
    text = " ".join(f"token{i}" for i in range(200 + q.SHINGLE - 1))
    assert np.mean(q.minhash(text) == q.minhash(text + " finalword")) > .95


def test_bom_evaluation_preserves_hash_and_stack_provenance(tmp_path):
    path = tmp_path / "evaluation.json"
    record = {"provenance": {"document_id": "stack-private-row-123"}, "messages": [
        {"role": "system", "content": "Python source only in this message"},
        {"role": "user", "content": "What does this function do?"}]}
    raw = b"\xef\xbb\xbf" + json.dumps(record).encode()
    path.write_bytes(raw)
    found = q.Contamination.from_paths([path])
    assert found.problem("unrelated short source", "stack-private-row-123") == "eval_document"
    assert found.source_sha256[path.as_posix()] == hashlib.sha256(raw).hexdigest()


def test_lsh_collisions_preserve_all_candidate_signatures(monkeypatch):
    signatures = iter([np.zeros(q.NUM_PERM, dtype=np.uint32), np.ones(q.NUM_PERM, dtype=np.uint32),
                       np.array([1] * 90 + [2] * 22, dtype=np.uint32)])
    monkeypatch.setattr(q, "minhash", lambda text: next(signatures))
    monkeypatch.setattr(q.xxhash, "xxh64_intdigest", lambda value: 0)
    index = q.NearDuplicateIndex()
    assert not index.check_and_add("first")
    assert not index.check_and_add("second")
    assert index.check_and_add("matches second, not first")


def test_lexicon_does_not_learn_validation_vocabulary(tmp_path):
    source = tmp_path / "boe.jsonl"
    train = "palabratrain repetida en el texto de entrenamiento"
    for index in range(10000):
        validation = f"palabravalidacion exclusiva en el texto {index}"
        if bc.holdout(hashlib.sha256(validation.encode()).hexdigest()):
            break
    assert not bc.holdout(hashlib.sha256(train.encode()).hexdigest())
    write(source, [{"document_id": "train", "text": train}, {"document_id": "val", "text": validation}])
    lexicon = tmp_path / "lexicon.txt"
    meta = bc.write_lexicon([bc.SourceSpec("BOE", source, "boe", "x")], lexicon, boe_min=1)
    words = set(lexicon.read_text().split())
    assert "palabratrain" in words and "palabravalidacion" not in words
    assert meta["partition"] == "train-only"


def test_near_duplicates_are_detected_and_distinct_texts_kept():
    index = q.NearDuplicateIndex()
    base = prose(14, 80)
    assert not index.check_and_add(base)
    words = base.split()
    edited = " ".join(words[:-3] + ["final", "distinto", "aquí"])  # a few words changed: same document
    assert index.check_and_add(edited)
    assert not index.check_and_add(prose(15, 80))


def test_decontamination_by_document_id_and_question_spans(tmp_path):
    holdout = tmp_path / "holdout.jsonl"
    question = ("Con los datos de la ficha indícame el tipo de disposición del Real Decreto y la fecha exacta "
                "en que se publicó en el boletín")
    system = ("Eres HYDRA.\nFUENTE:\nIdentificador: BOE-A-2006-1\nde conformidad con lo dispuesto en el artículo "
              "anterior la autoridad competente resolverá en el plazo de tres meses desde la solicitud")
    write(holdout, [{"messages": [{"role": "system", "content": system}, {"role": "user", "content": question},
                                  {"role": "assistant", "content": "Real Decreto."}]}])
    found = q.Contamination.from_paths([holdout])
    assert found.problem(prose(16), "BOE-A-2006-1") == "eval_document"
    assert found.problem(prose(16) + " " + question + ".", "BOE-A-2020-9") == "eval_overlap"
    # legal boilerplate quoted in the evaluated source does not knock out other laws
    assert found.problem(prose(16) + " " + system.split("\n")[-1], "BOE-A-2020-9") is None


def test_build_reports_filters_and_applies_near_dedup_and_decontamination(tmp_path):
    boe = tmp_path / "boe.jsonl"
    text = "Artículo 1. Objeto.\n" + prose(17, 30)
    near = text[:text.rstrip().rfind(" ")] + " cambio."  # only the last word differs
    write(boe, [{"document_id": "BOE-A-2020-1", "text": text}, {"document_id": "BOE-A-2020-2", "text": near},
                {"document_id": "BOE-A-2020-3", "text": "Artículo 1. Objeto.\n" + prose(18, 30)}])
    holdout = tmp_path / "cases.json"
    holdout.write_text(json.dumps([{"prompt": "Fuente BOE-A-2020-3"}]), encoding="utf-8")
    lexicon = tmp_path / "lexicon.txt"
    sources = [bc.SourceSpec("BOE", boe, "boe", "x")]
    meta = bc.write_lexicon(sources, lexicon, boe_min=1)
    assert meta["words"] > 10 and lexicon.with_suffix(".json").exists()
    report = bc.build(tmp_path / "hydra-base-corpus-vt", sources, q.Contamination.from_paths([holdout]), lexicon)
    assert report["version"] == "hydra-base-corpus-vt"
    assert report["sources"][0]["kept"] == 1
    assert report["sources"][0]["rejected"] == {"near_duplicate": 1, "eval_document": 1}
    filters = report["filters"]
    assert filters["decontamination"]["document_ids"] == 1 and filters["lexicon"]["sha256"] == meta["sha256"]
    assert filters["rules"]["boe"]["ngram_repetition"] is False and filters["near_duplicates"]["jaccard"] == 0.8
